services:
  ollama_stub:
    image: ghcr.io/embabel/embabel-llm-database-ollama-stub:latest
    networks:
      custom_net:
        ipv4_address: 172.20.0.10
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/api/tags || exit 1"]
      interval: 2s
      retries: 5

  embabel_llm_database:
    image: ghcr.io/embabel/embabel-llm-database:latest    
    environment:
      - SPRING_AI_OLLAMA_BASE-URL=http://172.20.0.10:11434   
    networks:
      custom_net:
        ipv4_address: 172.20.0.20      
    ports:
      - "8000:8000"
    depends_on:
      ollama_stub:
        condition: service_healthy

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1